### PR TITLE
chore: fork-a-🕓

### PR DESCRIPTION
**Pull request by drahnr**
Since roughly a year we've been attempting to find a way to work with upstream, but it seems there is a lack of resources to just review PRs.

Given the need on our end to significantly adapt the internal structure, this is sub optimal which lead to this PR.

I wanted to defer this to the latest point, but it seems the time has come. I'd rather not.

### CODE REVIEW

**Comment by Xanewok** [comment]
It's also worth noting that the `cc` internally hardcodes valid wrappers, which includes `sccache`:
https://github.com/alexcrichton/cc-rs/blob/c8b47ee8b53a57a505ecd0f0981c1bb3b4b58fb4/src/lib.rs#L2254
https://github.com/alexcrichton/cc-rs/blob/c8b47ee8b53a57a505ecd0f0981c1bb3b4b58fb4/src/lib.rs#L2207

So if we're 150% commited on a new name and a new 'brand', we'd need to add ourselves to the list in order not to lose C/C++ build acceleration (in contrast with using vanilla `sccache` bin name)

**Comment by drahnr** [comment]
Good point, but I think that's for once we got a release out the door :)

**Comment by drahnr** [comment]
Rebased this onto master, should be merged after #86 and  #84

**Review by Xanewok — APPROVED** [review]

**Comment by drahnr** [comment]
:tada:

**Pull request merged**
