### PR TITLE
Use Rusoto for S3

### PR DESCRIPTION
**Pull request by Xanewok**
Based on https://github.com/mozilla/sccache/pull/869 and https://github.com/diem/sccache/tree/rusoto.

Closes #3 

@TriplEight just to double-check, we won't be using S3 in the near future ourselves, right?

### CODE REVIEW

**Review by drahnr — APPROVED** [review]
LGTM! Ty

**Comment by Xanewok** [comment]
@alnr are you using S3? If so, could you see if this fixes your issue? (Commenting since you asked about merging this in https://github.com/paritytech/cachepot/pull/3#issuecomment-890838623)

**Comment by TriplEight** [comment]
No, we did not plan it. Anyway, our caches are too heavy to sync them via an internet connection.

**Comment by drahnr** [comment]
@Xanewok the easiest way might be to spawn up a local minio instance.

**Comment by drahnr** [comment]
@alnr thanks for testing! @Xanewok imho this is good to go

**Comment by Xanewok** [comment]
Thanks everybody!

**Pull request merged**
